#!/bin/sh
ssh ubuntu@13.125.160.15 <<EOF
    cd ~/jenkins-tutorial2
    git pull origin master
    sshpass -p jh 
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install 15.9.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
EOF