#!/bin/sh
ssh ubuntu@13.125.160.15 <<EOF
    cd ~/jenkins-tutorial2
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.shnvm install 
    nvm install 15.9.0
    npm installnpm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF